services:
  app:
    build:
      context: ./backend
    command: npm start
    volumes:
      - ./backend:/usr/app/
      - /usr/app/node_modules
    environment:
      - DB_HOST=db
    ports:
      - '3000:3000'
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '5432:5432'
    volumes:
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql

  frontend:
    build:
      context: ./imdb-app
    volumes:
      - ./imdb-app:/usr/src/front
      - /usr/src/front/node_modules
    ports:
      - '3001:3001'
    command: npm start
    depends_on:
      - app
